"""
Cross-LLM audit (layer 2 of Human-in-the-loop QA): each model re-labels the other's rows.

Runs on Colab, once per auditor (Qwen checks Llama's rows, then Llama checks Qwen's):
    python -m src.qa.cross_llm_audit --auditor qwen
    python -m src.qa.cross_llm_audit --auditor llama

A seeded `cross_llm_audit.audit_fraction` of the filtered pool is audited. For every row the
auditor predicts the emotion label and judges whether the text reads naturally. Verdicts are
appended to <data-dir>/audit/cross_llm.jsonl together with the audited text; a re-run skips
rows whose current text was already audited, and the gate ignores verdicts on stale text.
"""

import argparse
from pathlib import Path

import pandas as pd

from ..data.synthetic.generate import read_jsonl, write_jsonl
from ..data.synthetic.llm_client import HFClient
from ..data.synthetic.prompts import build_audit_messages, parse_audit_response
from ..utils.config import load_config
from ..utils.config_schema import CrossLLMAuditParams, DatagenConfig, QAConfig
from ..utils.logger import get_logger, setup_logger

logger = get_logger("cross_llm_audit")

# The answer is one short JSON line; greedy decoding keeps the verdict deterministic.
AUDIT_MAX_NEW_TOKENS = 64


def select_cross_llm_rows(pool: pd.DataFrame, cfg: CrossLLMAuditParams) -> pd.DataFrame:
    """
    Pick the rows to audit. The acceptance gate calls this too, to check full coverage.

    Args:
        pool: Filtered pool, in the order of filtered/pool.jsonl
        cfg: cross_llm_audit block of the QA config

    Returns:
        The audited subset of `pool`
    """
    return pool.sample(frac=cfg.audit_fraction, random_state=cfg.seed)


def run_cross_llm_audit(
    auditor: str,
    data_dir: str = "data/synthetic",
    datagen_config_path: str = "configs/datagen_config.yaml",
    qa_config_path: str = "configs/qa_config.yaml",
) -> None:
    """
    Audit the selected rows generated by the other model.

    Args:
        auditor: Key under `models` in the datagen config of the auditing model
        data_dir: Synthetic data root (reads filtered/pool.jsonl, writes audit/cross_llm.jsonl)
        datagen_config_path: Path to datagen config YAML (model ids, batch size)
        qa_config_path: Path to QA config YAML
    """
    datagen = DatagenConfig(**load_config(datagen_config_path))
    qa = QAConfig(**load_config(qa_config_path)).cross_llm_audit
    if auditor not in datagen.models:
        raise ValueError(f"Unknown auditor {auditor!r}, expected one of {sorted(datagen.models)}")

    pool = pd.DataFrame(read_jsonl(Path(data_dir) / "filtered" / "pool.jsonl"))
    selected = select_cross_llm_rows(pool, qa)
    output_file = Path(data_dir) / "audit" / "cross_llm.jsonl"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    done = (
        {(r["id"], r["text"]) for r in read_jsonl(output_file)} if output_file.exists() else set()
    )
    is_done = [key in done for key in zip(selected["id"], selected["text"], strict=True)]
    todo = selected[(selected["model"] != auditor) & ~pd.Series(is_done, index=selected.index)]
    logger.info(f"Selected {len(selected)}/{len(pool)} rows; {len(todo)} left for {auditor}")
    if todo.empty:
        return

    model_id = datagen.models[auditor].hf_model_id
    client = HFClient(model_id, load_in_4bit=datagen.generation.load_in_4bit)
    batch_size = datagen.generation.batch_size

    for start in range(0, len(todo), batch_size):
        batch = todo.iloc[start : start + batch_size]
        outputs = client.generate(
            [build_audit_messages(text) for text in batch["text"]],
            max_new_tokens=AUDIT_MAX_NEW_TOKENS,
        )
        rows = []
        for row_id, text, (raw, _truncated) in zip(
            batch["id"], batch["text"], outputs, strict=True
        ):
            predicted_label, natural = parse_audit_response(raw)
            rows.append(
                {
                    "id": row_id,
                    "text": text,
                    "auditor": auditor,
                    "auditor_model_id": model_id,
                    "predicted_label": predicted_label,
                    "natural": natural,
                    "raw_response": raw,
                }
            )
        write_jsonl(output_file, rows, append=True)
        logger.info(f"{auditor}: {min(start + batch_size, len(todo))}/{len(todo)}")

    logger.info(f"Cross-LLM audit by {auditor} complete -> {output_file}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--auditor", required=True, help="Key under `models` (llama / qwen)")
    parser.add_argument("--data-dir", default="data/synthetic")
    parser.add_argument("--datagen-config", default="configs/datagen_config.yaml")
    parser.add_argument("--qa-config", default="configs/qa_config.yaml")
    args = parser.parse_args()

    setup_logger()
    run_cross_llm_audit(args.auditor, args.data_dir, args.datagen_config, args.qa_config)
